version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "4800:4800"
    environment:
      - CLIENT_URL=http://client:4810
    networks:
      - medialab-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4800/"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "4810:4810"
    environment:
      - SERVER_URL=http://server:4800
    networks:
      - medialab-network
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4810/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  medialab-network:
    driver: bridge 