version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "4800:4800"
    volumes:
      - ./server:/app
      - ./common:/app/common
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    command: uvicorn src.main:app --host 0.0.0.0 --port 4800 --reload

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "4810:4810"
    volumes:
      - ./client:/app
      - ./common:/app/common
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - SERVER_URL=http://server:4800
    depends_on:
      - server
    command: uvicorn src.main:app --host 0.0.0.0 --port 4810 --reload 